name: Generate Gopher Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Generate Gopher SVG
        run: bun run generate:gopher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER_NAME: ${{ github.repository_owner }}

      - name: Push Gopher SVG to Repository
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
